In [ ]:
from __future__ import unicode_literals
#from gensim.summarization import keywords
import pandas as pd
import string
import nltk
from nltk.corpus import stopwords
nltk.download('punkt')
nltk.download('stopwords')
import pdb
import string
import matplotlib.pyplot as plt
from nltk.stem.porter import PorterStemmer
import unicodedata
!pip install sumy
import re

from sumy.parsers.plaintext import PlaintextParser
from sumy.nlp.tokenizers import Tokenizer
from sumy.summarizers.lex_rank import LexRankSummarizer

df =pd.read_csv('./JD_DataScience_USA_small_1.csv', encoding= 'unicode_escape')
df1 = pd.read_csv('./Resume_DataScience_Updated.csv', encoding= 'unicode_escape')

jd = df['description'].tolist()
companies = df['company'].tolist()
positions = df['title'].tolist()
#print(jd[0])

resume = df1['Resume'].tolist()
#print(resume[0])

cleanedjd = [x for x in jd if str(x) != 'nan']
cleanedresume = [x for x in resume if str(x) != 'nan']




[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [ ]:
cleanedresume

["CAREER SUMMARYCAREER SUMMARY\nAs a graduate student in data science. Seeking an Internship in Tesla as a Sales Data Science Internship (Fall 2023). Superb attention to detail, highly skilled in Python, R, data wrangling, SQL, data analytics, data visualization, Big Data, and machine learning with 6 years of experience as a Software Engineer.\nEDUCATION\nUniversity of North Texas | Denton, TX Expected: May 2024\nMaster of Science, Data Science GPA: 3.85\nRelevant Course Work: Data Visualization, Data Analytics, Data Science techniques, Machine Learning, Data Mining\nPrasad V. Potluri Siddhartha Institute of Technology | Vijayawada May 2017\nBachelor of Technology: Electronics and Computer Engineering GPA: 3.42\nSkills\nLanguages: Python, R, SQL, PL/SQL, PowerShell\nMicro Controller: Raspberry Pi\nFrameworks: MVC, Web API\nDatabases: MySQL\nBigdata Ecosystems: Hadoop, HDFS, HBase, Hive, Spark, Kafka\nData Visualizations: Tableau\nCloud technologies: AWS, GCP\nNO SQL Databases: Cassandr

In [ ]:
nltk.download('stopwords')

def preprocess_text(text):
    # lowercase
    #pdb.set_trace()
    text = text.lower()

    # Remove special characters using regular expression
    text = re.sub(r'[^a-zA-Z0-9\s]', '', text)
    # Check characters to see if they are in punctuation
    text = [char for char in text if char not in string.punctuation]

    # Join the characters again to form the string.
    text = ''.join(text)

    #print(nopunc)
    from nltk.corpus import stopwords
    stopwords.words('english')[0:200] # Show some stop words
    text.split()

    # Now just remove any stopwords
    text = [word for word in text.split() if word.lower() not in stopwords.words('english')]
    print(text)
    sentence = ' '.join(text)

    print(sentence)


    # # remove special characters and digits
    # #text = re.sub('[^a-zA-Z]+', ' ', text)

    # # remove stopwords
    # stop_words = set(stopwords.words('english'))
    # tokens = text.split()
    # filtered_tokens = [token for token in tokens if token not in stop_words]
    # text = ' '.join(filtered_tokens)

    # # remove extra spaces
    # text = re.sub('\s+', ' ', text).strip()

    # # remov puntuations
    # text = [char for char in text if char not in string.punctuation]

    return sentence


# apply the function to the JD and Resume columns of the dataframe
#cleanedjd = cleanedjd.apply(preprocess_text)
#cleanedresume = cleanedresume.apply(preprocess_text)


cleanedjd = [preprocess_text(element) for element in cleanedjd]
cleanedresume = [preprocess_text(element) for element in cleanedresume]

print(cleanedjd)
print(cleanedresume)



[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


['data', 'scientist', 'meta', 'shape', 'future', 'peoplefacing', 'businessfacing', 'products', 'build', 'across', 'entire', 'family', 'applications', 'facebook', 'instagram', 'messenger', 'whatsapp', 'oculus', 'applying', 'technical', 'skills', 'analytical', 'mindset', 'product', 'intuition', 'one', 'richest', 'data', 'sets', 'world', 'help', 'define', 'experiences', 'build', 'billions', 'people', 'hundreds', 'millions', 'businesses', 'around', 'world', 'collaborate', 'wide', 'array', 'product', 'business', 'problems', 'diverse', 'set', 'crossfunctional', 'partners', 'across', 'product', 'engineering', 'research', 'data', 'engineering', 'marketing', 'sales', 'finance', 'others', 'use', 'data', 'analysis', 'identify', 'solve', 'product', 'developments', 'biggest', 'challenges', 'influence', 'product', 'strategy', 'investment', 'decisions', 'data', 'focused', 'impact', 'collaborate', 'teams', 'joining', 'meta', 'become', 'part', 'worldclass', 'analytics', 'community', 'dedicated', 'skill

In [ ]:
cleanedjd = [x for x in cleanedjd if str(x) != 'nan']
print(len(cleanedjd))
cleanedresume = [x for x in cleanedresume if str(x) != 'nan']
print(len(cleanedresume))
cleanedjd.append(cleanedresume[0])

1
1


In [ ]:
print(cleanedjd[1])

In [ ]:
print(cleanedjd)

["As a Data Scientist at Meta, you will shape the future of people-facing and business-facing products we build across our entire family of applications (Facebook, Instagram, Messenger, WhatsApp, Oculus). By applying your technical skills, analytical mindset, and product intuition to one of the richest data sets in the world, you will help define the experiences we build for billions of people and hundreds of millions of businesses around the world. You will collaborate on a wide array of product and business problems with a diverse set of cross-functional partners across Product, Engineering, Research, Data Engineering, Marketing, Sales, Finance and others. You will use data and analysis to identify and solve product development\x83??s biggest challenges. You will influence product strategy and investment decisions with data, be focused on impact, and collaborate with other teams. By joining Meta, you will become part of a world-class analytics community dedicated to skill development

In [ ]:
### Easy — Sentence-Transformers
!pip install sentence_transformers
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

model = SentenceTransformer('bert-base-nli-mean-tokens')
sentence_embeddings = model.encode(cleanedjd)
sentence_embeddings.shape
cosine_similarity(
    [sentence_embeddings[0]],
    sentence_embeddings[1:]
)



     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.0/86.0 kB 8.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.2/7.2 MB 87.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 46.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 268.8/268.8 kB 24.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 23.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 39.7 MB/s eta 0:00:00
ERROR: Operation cancelled by user


ModuleNotFoundError: ignored

In [ ]:
model = SentenceTransformer('roberta-base-nli-mean-tokens')
sentence_embeddings = model.encode(cleanedjd)
sentence_embeddings.shape
cosine_similarity(
    [sentence_embeddings[0]],
    sentence_embeddings[1:]
)

array([[0.7932164]], dtype=float32)

In [ ]:
model = SentenceTransformer('distilbert-base-nli-mean-tokens')
sentence_embeddings = model.encode(cleanedjd)
sentence_embeddings.shape
cosine_similarity(
    [sentence_embeddings[0]],
    sentence_embeddings[1:]
)

array([[0.70384794]], dtype=float32)

In [ ]:
### Involved — Transformers And PyTorch
from transformers import AutoTokenizer, AutoModel
import torch

tokenizer = AutoTokenizer.from_pretrained('sentence-transformers/bert-base-nli-mean-tokens')
model = AutoModel.from_pretrained('sentence-transformers/bert-base-nli-mean-tokens')

# initialize dictionary to store tokenized sentences
tokens = {'input_ids': [], 'attention_mask': []}

for sentence in cleanedjd:
    # encode each sentence and append to dictionary
    new_tokens = tokenizer.encode_plus(sentence, max_length=128,
                                       truncation=True, padding='max_length',
                                       return_tensors='pt')
    tokens['input_ids'].append(new_tokens['input_ids'][0])
    tokens['attention_mask'].append(new_tokens['attention_mask'][0])

# reformat list of tensors into single tensor
tokens['input_ids'] = torch.stack(tokens['input_ids'])
tokens['attention_mask'] = torch.stack(tokens['attention_mask'])

In [ ]:
outputs = model(**tokens)
outputs.keys()

embeddings = outputs.last_hidden_state
print(embeddings)
print(embeddings.shape)
attention_mask = tokens['attention_mask']
print(attention_mask.shape)
mask = attention_mask.unsqueeze(-1).expand(embeddings.size()).float()
mask.shapemask = attention_mask.unsqueeze(-1).expand(embeddings.size()).float()
print(mask.shape)
print(mask)
masked_embeddings = embeddings * mask
print(masked_embeddings.shape)
print(masked_embeddings)
summed = torch.sum(masked_embeddings, 1)
print(summed.shape)
summed_mask = torch.clamp(mask.sum(1), min=1e-9)
summed_mask.shape
print(summed_mask)
mean_pooled = summed / summed_mask
print(mean_pooled)

tensor([[[-0.5830,  1.0707,  0.5089,  ..., -1.2843, -0.4788,  0.0600],
         [-0.5386,  1.0882,  0.5930,  ..., -1.5719, -0.6880, -0.2322],
         [-0.7451,  0.7701,  0.7026,  ..., -1.3677, -0.5939,  0.0967],
         ...,
         [-0.3357,  0.9774,  0.7566,  ..., -0.9269, -0.8362,  0.0953],
         [-0.4598,  1.4239,  1.3379,  ..., -1.3289, -0.8957, -0.0091],
         [-0.7091,  1.1196,  0.6385,  ..., -1.2849, -0.6713,  0.0757]],

        [[-0.7823,  0.6909,  0.9040,  ..., -0.4951,  0.0157,  0.3002],
         [-0.4209,  0.7429,  1.0324,  ..., -0.5019,  0.0898, -0.0803],
         [-0.1828,  0.8775,  0.8229,  ..., -0.5126, -0.1640, -0.1825],
         ...,
         [ 0.4287, -0.0219,  0.5612,  ..., -0.1903, -0.0626,  0.1689],
         [ 0.5454,  0.4541,  0.8881,  ..., -0.2860, -0.0067, -0.0410],
         [-0.6389,  0.7990,  0.8145,  ..., -0.4381,  0.0316,  0.0644]]],
       grad_fn=<NativeLayerNormBackward0>)
torch.Size([2, 128, 768])
torch.Size([2, 128])
torch.Size([2, 128, 768])


In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
# convert from PyTorch tensor to numpy array
mean_pooled = mean_pooled.detach().numpy()

# calculate
cosine_similarity(
    [mean_pooled[0]],
    mean_pooled[1:]
)

array([[0.7431299]], dtype=float32)

In [ ]:
from transformers import AutoTokenizer, AutoModel
import torch

tokenizer = AutoTokenizer.from_pretrained('sentence-transformers/roberta-base-nli-mean-tokens')
model = AutoModel.from_pretrained('sentence-transformers/roberta-base-nli-mean-tokens')

# initialize dictionary to store tokenized sentences
tokens = {'input_ids': [], 'attention_mask': []}

for sentence in cleanedjd:
    # encode each sentence and append to dictionary
    new_tokens = tokenizer.encode_plus(sentence, max_length=128,
                                       truncation=True, padding='max_length',
                                       return_tensors='pt')
    tokens['input_ids'].append(new_tokens['input_ids'][0])
    tokens['attention_mask'].append(new_tokens['attention_mask'][0])

# reformat list of tensors into single tensor
tokens['input_ids'] = torch.stack(tokens['input_ids'])
tokens['attention_mask'] = torch.stack(tokens['attention_mask'])


In [ ]:
outputs = model(**tokens)
outputs.keys()

embeddings = outputs.last_hidden_state
print(embeddings)
print(embeddings.shape)
attention_mask = tokens['attention_mask']
print(attention_mask.shape)
mask = attention_mask.unsqueeze(-1).expand(embeddings.size()).float()
mask.shapemask = attention_mask.unsqueeze(-1).expand(embeddings.size()).float()
print(mask.shape)
print(mask)
masked_embeddings = embeddings * mask
print(masked_embeddings.shape)
print(masked_embeddings)
summed = torch.sum(masked_embeddings, 1)
print(summed.shape)
summed_mask = torch.clamp(mask.sum(1), min=1e-9)
summed_mask.shape
print(summed_mask)
mean_pooled = summed / summed_mask
print(mean_pooled)

tensor([[[-0.5784, -0.5513,  0.0344,  ..., -2.2032, -0.0161,  0.6560],
         [-0.7274, -0.3689, -0.0117,  ..., -2.4069,  0.0160,  0.9737],
         [-0.6746, -0.3492, -0.0403,  ..., -2.5339, -0.0359,  1.0232],
         ...,
         [-0.4418, -0.5986,  0.0668,  ..., -1.5485,  0.0565,  0.5122],
         [-0.2777, -0.5187,  0.1115,  ..., -1.9411,  0.0900,  0.6695],
         [-0.4705, -0.5723,  0.1119,  ..., -1.8632, -0.0131,  0.5879]],

        [[-0.5518, -0.6664, -0.0602,  ..., -1.9434,  0.2376,  0.5617],
         [-0.8339, -0.4897,  0.0681,  ..., -2.1592,  0.2123,  1.3282],
         [-0.7712, -0.5131, -0.0646,  ..., -2.6294,  0.3032,  0.9309],
         ...,
         [-0.7918, -0.6122,  0.1974,  ..., -2.8696,  0.1535,  0.4982],
         [-0.5551, -0.5047,  0.0755,  ..., -2.6470,  0.1052,  0.7092],
         [-0.5165, -0.8297, -0.0548,  ..., -1.6063,  0.2637,  0.4824]]],
       grad_fn=<NativeLayerNormBackward0>)
torch.Size([2, 128, 768])
torch.Size([2, 128])
torch.Size([2, 128, 768])


In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
# convert from PyTorch tensor to numpy array
mean_pooled = mean_pooled.detach().numpy()

# calculate
cosine_similarity(
    [mean_pooled[0]],
    mean_pooled[1:]
)

array([[0.74429727]], dtype=float32)

In [ ]:
from transformers import AutoTokenizer, AutoModel
import torch

tokenizer = AutoTokenizer.from_pretrained('sentence-transformers/distilbert-base-nli-mean-tokens')
model = AutoModel.from_pretrained('sentence-transformers/distilbert-base-nli-mean-tokens')

# initialize dictionary to store tokenized sentences
tokens = {'input_ids': [], 'attention_mask': []}

for sentence in cleanedjd:
    # encode each sentence and append to dictionary
    new_tokens = tokenizer.encode_plus(sentence, max_length=128,
                                       truncation=True, padding='max_length',
                                       return_tensors='pt')
    tokens['input_ids'].append(new_tokens['input_ids'][0])
    tokens['attention_mask'].append(new_tokens['attention_mask'][0])

# reformat list of tensors into single tensor
tokens['input_ids'] = torch.stack(tokens['input_ids'])
tokens['attention_mask'] = torch.stack(tokens['attention_mask'])

In [ ]:
outputs = model(**tokens)
outputs.keys()

embeddings = outputs.last_hidden_state
print(embeddings)
print(embeddings.shape)
attention_mask = tokens['attention_mask']
print(attention_mask.shape)
mask = attention_mask.unsqueeze(-1).expand(embeddings.size()).float()
mask.shapemask = attention_mask.unsqueeze(-1).expand(embeddings.size()).float()
print(mask.shape)
print(mask)
masked_embeddings = embeddings * mask
print(masked_embeddings.shape)
print(masked_embeddings)
summed = torch.sum(masked_embeddings, 1)
print(summed.shape)
summed_mask = torch.clamp(mask.sum(1), min=1e-9)
summed_mask.shape
print(summed_mask)
mean_pooled = summed / summed_mask
print(mean_pooled)

tensor([[[ 0.4011, -0.3068,  0.5735,  ..., -0.2473, -0.0277, -0.8648],
         [ 0.5902, -0.1502,  0.7235,  ..., -0.1900,  0.0540, -0.8482],
         [ 0.3020, -0.1903,  0.5493,  ..., -0.0288,  0.1718, -0.8867],
         ...,
         [ 0.2927, -0.1516,  0.9279,  ...,  0.0242, -0.2565, -0.7717],
         [ 0.4844, -0.2315,  0.9188,  ..., -0.3751, -0.3983, -0.9790],
         [ 0.2242, -0.2053,  0.8436,  ..., -0.1355, -0.1241, -0.8618]],

        [[-0.0686, -0.4058,  0.9029,  ...,  0.1224, -0.2200, -0.2999],
         [-0.1078, -0.3121,  0.8703,  ...,  0.4476,  0.3987, -0.4428],
         [-0.1170, -0.3753,  0.8306,  ...,  0.2816,  0.1076, -0.3913],
         ...,
         [ 0.0426, -0.5112,  0.8067,  ...,  0.3647,  0.3725, -0.1245],
         [-0.0333, -0.3364,  1.3023,  ...,  0.2175,  0.3013, -0.2321],
         [-0.3347, -0.2724,  0.8851,  ...,  0.2300, -0.0165, -0.3071]]],
       grad_fn=<NativeLayerNormBackward0>)
torch.Size([2, 128, 768])
torch.Size([2, 128])
torch.Size([2, 128, 768])


In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
# convert from PyTorch tensor to numpy array
mean_pooled = mean_pooled.detach().numpy()

# calculate
cosine_similarity(
    [mean_pooled[0]],
    mean_pooled[1:]
)

array([[0.7043916]], dtype=float32)

In [ ]:


# Input text
#text = '''
#As a Data Scientist at Meta, you will shape the future of people-facing and business-facing products we build across our entire family of applications (Facebook, Instagram, Messenger, WhatsApp, Oculus). By applying your technical skills, analytical mindset, and product intuition to one of the richest data sets in the world, you will help define the experiences we build for billions of people and hundreds of millions of businesses around the world. You will collaborate on a wide array of product and business problems with a diverse set of cross-functional partners across Product, Engineering, Research, Data Engineering, Marketing, Sales, Finance and others. You will use data and analysis to identify and solve product developmentƒ??s biggest challenges. You will influence product strategy and investment decisions with data, be focused on impact, and collaborate with other teams. By joining Meta, you will become part of a world-class analytics community dedicated to skill development and career growth in analytics and beyond.Product leadership: You will use data to shape product development, quantify new opportunities, identify upcoming challenges, and ensure the products we build bring value to people, businesses, and Meta. You will help your partner teams prioritize what to build, set goals, and understand their productƒ??s ecosystem.Analytics: You will guide teams using data and insights. You will focus on developing hypotheses and employ a diverse toolkit of rigorous analytical approaches, different methodologies, frameworks, and technical approaches to test them.Communication and influence: You wonƒ??t simply present data, but tell data-driven stories. You will convince and influence your partners using clear insights and recommendations. You will build credibility through structure and clarity, and be a trusted strategic partner.Data Scientist, Product Analytics Responsibilities:Work with large and complex data sets to solve a wide array of challenging problems using different analytical and statistical approaches.Apply technical expertise with quantitative analysis, experimentation, data mining, and the presentation of data to develop strategies for our products that serve billions of people and hundreds of millions of businesses.Identify and measure success of product efforts through goal setting, forecasting, and monitoring of key product metrics to understand trends.Define, understand, and test opportunities and levers to improve the product, and drive roadmaps through your insights and recommendations.Partner with Product, Engineering, and cross-functional teams to inform, influence, support, and execute product strategy and investment decisions.Minimum Qualifications:Bachelor's degree in Mathematics, Statistics, a relevant technical field, or equivalent practical experience.A minimum of 2 years of work experience in analytics (minimum of 1 years with a Ph.D.)Experience with data querying languages (e.g. SQL), scripting languages (e.g. Python), and/or statistical/mathematical software (e.g. R)Preferred Qualifications:Masters or Ph.D. Degree in a quantitative field.Meta is proud to be an Equal Employment Opportunity and Affirmative Action employer. We do not discriminate based upon race, religion, color, national origin, sex (including pregnancy, childbirth, reproductive health decisions, or related medical conditions), sexual orientation, gender identity, gender expression, age, status as a protected veteran, status as an individual with a disability, genetic information, political views or activity, or other applicable legally protected characteristics. You may view our Equal Employment Opportunity notice here. We also consider qualified applicants with criminal histories, consistent with applicable federal, state and local law. We may use your information to maintain the safety and security of Meta, its employees, and others as required or permitted by law. You may view Meta's Pay Transparency Policy, Equal Employment Opportunity is the Law notice, and Notice to Applicants for Employment and Employees by clicking on their corresponding links. Additionally, Meta participates in the E-Verify program in certain locations, as required by law
#'''

# Initialize the parser and tokenizer
parser = PlaintextParser.from_string(resume[0], Tokenizer("english"))

# Initialize the summarizer (LexRank)
summarizer = LexRankSummarizer()

# Generate the summary
summary_sentences = summarizer(parser.document, 2)  # Number of sentences in the summary

# Print the summarized text
summary = " ".join([str(sentence) for sentence in summary_sentences])
print(summary)

parser1 = PlaintextParser.from_string(jd, Tokenizer("english"))


# Generate the summary
summary_sentences1 = summarizer(parser1.document, 2)  # Number of sentences in the summary

# Print the summarized text JD
summary1 = " ".join([str(sentence1) for sentence1 in summary_sentences1])
print(summary1)


Implemented a model to Predict the sales using NumPy, Pandas, scikit-learn, seaborn, matplotlib, Regression models to evaluate the performance and accuracy using MSE & RMSE. • Involved in the entire data science project life cycle and actively involved in all the phases including data extraction, data cleaning, statistical modelling, and data visualization with large data sets of structured and unstructured data.
You will build credibility through structure and clarity, and be a trusted strategic partner.Data Scientist, Product Analytics Responsibilities:Work with large and complex data sets to solve a wide array of challenging problems using different analytical and statistical approaches.Apply technical expertise with quantitative analysis, experimentation, data mining, and the presentation of data to develop strategies for our products that serve billions of people and hundreds of millions of businesses.Identify and measure success of product efforts through goal setting, forecastin

In [ ]:

# Check characters to see if they are in punctuation
nopunc = [char for char in summary if char not in string.punctuation]

# Join the characters again to form the string.
nopunc = ''.join(nopunc)

#print(nopunc)
from nltk.corpus import stopwords
stopwords.words('english')[0:200] # Show some stop words
nopunc.split()

# Now just remove any stopwords
clean_mess = [word for word in nopunc.split() if word.lower() not in stopwords.words('english')]
print(clean_mess)
###################################################

nopunc1 = [char for char in summary1 if char not in string.punctuation]

# Join the characters again to form the string.
nopunc1 = ''.join(nopunc1)

#print(nopunc)
from nltk.corpus import stopwords
stopwords.words('english')[0:200] # Show some stop words
nopunc1.split()

# Now just remove any stopwords
clean_mess1 = [word1 for word1 in nopunc1.split() if word1.lower() not in stopwords.words('english')]
print(clean_mess1)



['Implemented', 'model', 'Predict', 'sales', 'using', 'NumPy', 'Pandas', 'scikitlearn', 'seaborn', 'matplotlib', 'Regression', 'models', 'evaluate', 'performance', 'accuracy', 'using', 'MSE', 'RMSE', '\x95', 'Involved', 'entire', 'data', 'science', 'project', 'life', 'cycle', 'actively', 'involved', 'phases', 'including', 'data', 'extraction', 'data', 'cleaning', 'statistical', 'modelling', 'data', 'visualization', 'large', 'data', 'sets', 'structured', 'unstructured', 'data']
['build', 'credibility', 'structure', 'clarity', 'trusted', 'strategic', 'partnerData', 'Scientist', 'Product', 'Analytics', 'ResponsibilitiesWork', 'large', 'complex', 'data', 'sets', 'solve', 'wide', 'array', 'challenging', 'problems', 'using', 'different', 'analytical', 'statistical', 'approachesApply', 'technical', 'expertise', 'quantitative', 'analysis', 'experimentation', 'data', 'mining', 'presentation', 'data', 'develop', 'strategies', 'products', 'serve', 'billions', 'people', 'hundreds', 'millions', 'bu

In [ ]:
!pip install transformers
!pip install torch

import torch
from transformers import BertTokenizer, BertModel

# Load pre-trained BERT model and tokenizer
model_name = 'bert-base-uncased'
tokenizer = BertTokenizer.from_pretrained(model_name)
model = BertModel.from_pretrained(model_name)

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.2/7.2 MB 48.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 268.8/268.8 kB 25.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 65.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 46.6 MB/s eta 0:00:00


Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.bias', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [ ]:
# Define function to convert text to BERT embeddings
def get_bert_embedding(text):
    input_ids = torch.tensor(tokenizer.encode(text)).unsqueeze(0)
    outputs = model(input_ids)
    last_hidden_states = outputs.last_hidden_state
    embedding = torch.mean(last_hidden_states, dim=1)
    return embedding.detach().numpy()[0]

In [ ]:
import numpy as np
jdd = np.mean([get_bert_embedding(w) for w in cleanedjd], axis=0)
ress = np.mean([get_bert_embedding(w) for w in cleanedresume], axis=0)

from sklearn.metrics.pairwise import cosine_similarity
cosine_similarity(
    [ress],
    [jdd]
)


Token indices sequence length is longer than the specified maximum sequence length for this model (974 > 512). Running this sequence through the model will result in indexing errors


RuntimeError: ignored

In [ ]:
from transformers import DistilBertTokenizer, DistilBertModel

# Load pre-trained DistilBERT model and tokenizer
tokenizer = DistilBertTokenizer.from_pretrained('distilbert-base-uncased')
model = DistilBertModel.from_pretrained('distilbert-base-uncased')

Some weights of the model checkpoint at distilbert-base-uncased were not used when initializing DistilBertModel: ['vocab_projector.bias', 'vocab_transform.bias', 'vocab_transform.weight', 'vocab_layer_norm.bias', 'vocab_layer_norm.weight']
- This IS expected if you are initializing DistilBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing DistilBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [ ]:
# Define function to convert text to BERT embeddings
def get_bert_embedding(text):
    input_ids = torch.tensor(tokenizer.encode(text)).unsqueeze(0)
    outputs = model(input_ids)
    last_hidden_states = outputs.last_hidden_state
    embedding = torch.mean(last_hidden_states, dim=1)
    return embedding.detach().numpy()[0]

In [ ]:
import numpy as np
ress = np.mean([get_bert_embedding(w) for w in clean_mess], axis=0)
jdd = np.mean([get_bert_embedding(w) for w in clean_mess1], axis=0)

from sklearn.metrics.pairwise import cosine_similarity
cosine_similarity(
    [ress],
    [jdd]
)


array([[0.996064]], dtype=float32)